### ISSUE TITLE
The latest release does not have audio support

### ISSUE THREAD

**Issue by Phoenixx19** [NicusorN5/Fast-XNB-Builder#1]
I realized you probably forgot to put a new release.
Because the debug commit uploaded in April actually works with audio too!
Anyway great program, thank you.

**Comment by Phoenixx19** [comment]
Resolved with new branch. Don't forget to put a new release!

**Comment by NicusorN5** [comment]
I was missing for a while, I didn't expect anyone using this. Glad to see ya there!
